INSERT INTO USER_ENTITY VALUES(1, 'KRISHNA');
INSERT INTO USER_ENTITY VALUES(2, 'RADHA');
INSERT INTO USER_ENTITY VALUES(3, 'LOHIT');
INSERT INTO USER_ENTITY VALUES(4, 'ARJUN');
INSERT INTO USER_ENTITY VALUES(5, 'CARYN');
INSERT INTO USER_ENTITY VALUES(6, 'GAUTAM');
INSERT INTO USER_ENTITY VALUES(7, 'PROTTAY');