INSERT INTO USERS VALUES(1, 'KRISHNA');
INSERT INTO USERS VALUES(2, 'RADHA');
INSERT INTO USERS VALUES(3, 'LOHIT');
INSERT INTO USERS VALUES(4, 'ARJUN');
INSERT INTO USERS VALUES(5, 'CARYN');
INSERT INTO USERS VALUES(6, 'GAUTAM');
INSERT INTO USERS VALUES(7, 'PROTTAY');